// ─── generatingStatements.ts ─────────────────────────────────────────────────
//
// All progress bar statement arrays for GeneratingBar.tsx.
// Import whichever array matches your context and pass it as the `statements` prop.
//
// Usage:
//   import { JURY_EVAL_STATEMENTS } from '@/lib/generatingStatements'
//   <GeneratingBar isGenerating={isLoading} statements={JURY_EVAL_STATEMENTS} estimatedDuration={50000} />
//
// Suggested estimatedDuration values:
//   DEFAULT_STATEMENTS          → 50000–60000ms  (draft generation)
//   MATERIALS_EVAL_STATEMENTS   → 40000ms
//   JURY_EVAL_STATEMENTS        → 50000ms
//   COACH_REVIEW_STATEMENTS     → 50000ms
//   SCRIPT_GENERATE_STATEMENTS  → 60000ms
//   SCRIPT_REVIEW_STATEMENTS    → 50000ms
// ─────────────────────────────────────────────────────────────────────────────


// ─── Default (Draft Generation) ──────────────────────────────────────────────

export const DEFAULT_STATEMENTS: string[] = [
  'Polishing words until they blind the jury.',
  'Finding synonyms for "groundbreaking" and "unprecedented."',
  'Making good work sound like great work.',
  'Replacing "we made an ad" with poetry.',
  'Adding gravitas to an already grave situation.',
  'Sprinkling in just enough humility to seem humble.',
  'Choosing words that echo in judging rooms.',
  'Turning bullet points into prose worth reading.',
  'Making the obvious sound like a revelation.',
  'Giving the brief a proper origin story.',
  'Thinking about what judges eat for breakfast.',
  'Anticipating the judge who skims everything.',
  'Writing for the jury member half-asleep.',
  'Calibrating tone for underpaid, overcaffeinated jurors.',
  'Channeling what a Grand Prix winner sounds like.',
  'Imagining twelve strangers debating your entry.',
  'Making sure London jurors get the reference.',
  'Adjusting for juries who\'ve seen it all.',
  'Writing as if Cannes is watching. It is.',
  'Appealing to jurors who judge on instinct.',
  'Reminding the entry the work is the hero.',
  'Contextualizing the insight nobody else would have found.',
  'Making the target audience sound worth caring about.',
  'Finding the human truth buried in the data.',
  'Inflating the cultural tension just a touch.',
  'Connecting the dots between brief and brilliance.',
  'Giving the results section its moment to shine.',
  'Making a modest budget sound like a choice.',
  'Framing the constraint as the creative catalyst.',
  'Turning "client liked it" into strategic alignment.',
  'Drafting. Deleting. Redrafting. Nearly there.',
  'Asking if this really needs another adjective.',
  'Considering if "disrupted" is the right verb.',
  'Second-guessing the opening line again.',
  'Editing for clarity. Also for drama.',
  'Checking the word count with quiet optimism.',
  'Re-reading the brief one final, unnecessary time.',
  'Making peace with the word "leverage."',
  'Running it through the pretension detector.',
  'Adding warmth without losing the sharp edge.',
  'Translating agency-speak into judging-room currency.',
  'Cross-referencing this year\'s winning entry themes.',
  'Verifying the campaign actually ran somewhere public.',
  'Making sure the results are technically defensible.',
  'Noting proudly it ran in more than one market.',
  'Quietly checking if anyone else entered this.',
  'Situating the work in the cultural moment.',
  'Giving the timeline a more flattering narrative arc.',
  'Distinguishing this from every other social campaign.',
  'Reminding the entry that humility is optional.',
  'Teaching a machine to care about craft.',
  'AI carefully not overselling. That\'s your job.',
  'Generating language no human would have chosen.',
  'Distilling your brief into something actually legible.',
  'Processing the nuance. Most of it, anyway.',
  'Asking the algorithm to channel David Abbott.',
  'Simulating the voice of a very confident strategist.',
  'Letting the machine draft; you edit ruthlessly.',
  'No shortcuts were taken. Mostly.',
  'Even the AI paused on that last line.',
  'Racing the deadline you set for yourself.',
  'Three days before entry close. Very normal.',
  'Submitting is the hardest part. Almost there.',
  'Turns out good writing takes actual time.',
  'Retroactively making this feel very planned.',
  'Reconstructing the timeline with generous rounding.',
  'Remembering why you entered this category.',
  'This would have been faster with more sleep.',
  'Entry closes in hours. You\'re fine. Probably.',
  'Finding the save button before time runs out.',
  'Making the numbers do more emotional lifting.',
  'Contextualizing the result against a very modest benchmark.',
  'Noting the uplift, which was real and measurable.',
  'Finding the metric that tells the best story.',
  'Making sure ROI is the supporting act, not the lead.',
  'Translating awareness into something a jury respects.',
  'Calculating the reach one more time, for confidence.',
  'Results don\'t lie. Framing does the rest.',
  'Giving the effectiveness section its rightful gravitas.',
  'Turning percentage points into proof of cultural impact.',
  'Considering whether this is actually a PR entry.',
  'Debating if "integrated" is still a real category.',
  'Reminding the entry it belongs in Titanium.',
  'Quietly hedging across three possible categories.',
  'This is definitely not just a print ad.',
  'Confirming the use of technology was intentional.',
  'Verifying this qualifies as "real-time" by any definition.',
  'Arguing for purpose without losing the product.',
  'Making the case for craft in a craft category.',
  'Noting this isn\'t social media. It\'s culture.',
  'Removing the phrase "as a brand, we believe."',
  'Striking "authentically" from the record. Again.',
  'Replacing "journey" with something less 2018.',
  'Deleting the word "holistic" out of principle.',
  'Quietly removing three unnecessary exclamation marks.',
  'Considering whether "storytelling" still means anything.',
  'Making the CEO quote sound slightly less corporate.',
  'Ensuring "disruptive" earns its place this time.',
  'Cutting the last paragraph. You know which one.',
  'Submitting with confidence. Mild, well-earned confidence.',
]


// ─── Materials — Evaluate as Entry ───────────────────────────────────────────

export const MATERIALS_EVAL_STATEMENTS: string[] = [
  'Hunting for the headline buried in here.',
  'Separating signal from very expensive noise.',
  'Looking for the idea under the idea.',
  'Checking if this shines or just glitters.',
  'Mining for the single most powerful moment.',
  'Asking: is this diamond rough or just rough?',
  'Finding what actually moved the needle here.',
  'Deciding what a jury actually needs to see.',
  'Sorting the showstopper from the supporting cast.',
  'Looking past the logo slides for the goods.',
  'Identifying which bit makes the case stick.',
  'Scanning for evidence that backs the big claim.',
  'Asking if the proof matches the promise.',
  'Checking if this is a campaign or a moment.',
  'Finding the part even the client loves.',
  'Separating genuine insight from retrofitted narrative.',
  'Figuring out what the brief was supposed to be.',
  'Locating the idea the results actually prove.',
  'Checking if this holds up without the music.',
  'Asking what a skeptic would need to believe.',
  'Deciding if the numbers support or just decorate.',
  'Looking for the moment that made someone care.',
  'Finding the thing competitors couldn\'t have done.',
  'Checking if lab-grown is an option here.',
  'Asking whether the brief was the actual problem.',
  'Identifying the insight before the client changed it.',
  'Sorting the genuine from the genuinely embellished.',
  'Deciding what deserves a slide of its own.',
  'Checking if the result was the real idea.',
  'Looking for the campaign hiding in the case study.',
  'Figuring out which part made headlines, intentionally.',
  'Finding what\'s culturally true vs. strategically convenient.',
  'Asking what the target audience actually did differently.',
  'Deciding if the tension in the brief was real.',
  'Looking for the honest version of this story.',
  'Checking if there\'s a reason to enter this.',
  'Finding the strongest three minutes in here.',
  'Asking: would this win if the result was smaller?',
  'Separating what happened from what you wished happened.',
  'Locating the moment worth building everything around.',
  'Checking if the big idea was always this obvious.',
  'Finding the brief behind the brief behind the brief.',
  'Asking if the execution elevated the strategy or hid it.',
  'Looking for what the creative team was actually proud of.',
  'Deciding which asset does the most work quietly.',
  'Checking if this works when the budget isn\'t visible.',
  'Finding the cultural moment this campaign actually owned.',
  'Asking if the client understood what they approved.',
  'Looking for the proof point that does triple duty.',
  'Checking if the brand role is earned or assumed.',
  'Finding what wouldn\'t have existed without this campaign.',
  'Asking if the problem was worth solving this way.',
  'Looking for the insight no one else had used yet.',
  'Deciding how much the media idea matters here.',
  'Checking if the campaign changed anything or just measured it.',
  'Finding the moment where this became more than advertising.',
  'Asking if the creative idea is visible in the results.',
  'Looking for the category tension that drove the brief.',
  'Checking if the headline result has a solid denominator.',
  'Finding what the audience gave back unprompted.',
  'Asking if this earned attention or bought it very noisily.',
  'Looking for the version of this that didn\'t require luck.',
  'Deciding which elements could survive a media-neutral brief.',
  'Checking if the strategy would make sense without the work.',
  'Finding the second-best idea that might be the real one.',
  'Asking if the craft is serving or compensating for the idea.',
  'Looking for what this campaign did that couldn\'t be undone.',
  'Checking if the before-and-after is actually believable.',
  'Finding the human truth at the center of all this.',
  'Asking whether the results section tells a consistent story.',
  'Looking for the one asset that would survive without context.',
  'Deciding if the category choice flatters or limits this entry.',
  'Checking if the brand was more famous after this campaign.',
  'Finding the detail that turns a good entry into a great one.',
  'Asking if the simplest version of this is the strongest.',
  'Looking for the claim that\'s hard to argue with.',
  'Checking if the creative execution is the actual innovation.',
  'Finding where the strategy and the creative actually meet.',
  'Asking if the audience did something or just felt something.',
  'Looking for the proof that scales the size of the claim.',
  'Checking if this campaign would be missed if it stopped.',
  'Finding the one thing that couldn\'t have been templated.',
  'Asking whether the problem was real or manufactured beautifully.',
  'Looking for the result that changed the conversation permanently.',
  'Deciding if the timing made the idea or the idea made timing.',
  'Checking if every asset is pulling in the same direction.',
  'Finding what a competitive brand would have been afraid of.',
  'Asking if there\'s enough here to fill the entry form honestly.',
  'Looking for the logic that connects spend to outcome cleanly.',
  'Checking whether the emotional claim is backed by behavioral data.',
  'Finding the part a sceptical planner would find compelling.',
  'Asking if this story works in a 90-second video.',
  'Looking for the idea that\'s bigger than the execution.',
  'Deciding if this is a product story pretending to be a brand story.',
  'Checking if the audience insight was actually used or just stated.',
  'Finding what this campaign added to culture, if anything.',
  'Asking if the brand would be proud of this in ten years.',
  'Looking for the earned media that proves the idea worked.',
  'Checking if the claim would survive a fact-check.',
  'Finding the version a cynical strategist would still respect.',
  'Asking if the best asset is actually in the submission.',
  'Looking for the competitive context that makes the win bigger.',
  'Checking if the brief question was the right one to answer.',
  'Finding the part where creativity solved a real business problem.',
  'Asking if the emotional and rational cases are both made.',
  'Looking for the result that wouldn\'t have happened without this.',
  'Checking if the tone of voice is consistent across all assets.',
  'Finding what stayed the same when the campaign changed everything.',
  'Asking whether the medium was part of the message here.',
  'Looking for the executional detail that proves genuine craft.',
  'Checking if the narrative has momentum or just milestones.',
  'Finding the three assets that do 80% of the heavy lifting.',
  'Asking if the entry is written as well as the campaign was made.',
  'Looking for the single number that makes the whole case.',
  'Checking if the cultural insight was timely or just timeless.',
  'Finding the version of this that would still work in five years.',
  'Asking if the brief was brave or just ambitious with a safety net.',
  'Looking for the proof that the idea had legs beyond the launch.',
  'Checking whether the audience was changed or just reached.',
  'Finding what makes this entry different from the shortlist pack.',
  'Asking if the strategy section sounds like it came first.',
  'Looking for the business problem that made this work matter.',
  'Checking if the long-term results section has legs.',
  'Finding the executional element that elevates everything around it.',
  'Asking if the idea was platform-native or just platform-present.',
  'Looking for the moment the campaign stopped being advertising.',
  'Checking if the results are proportionate to the ambition.',
  'Finding the one thing this campaign proved that no one expected.',
  'Asking whether the context section makes the achievement feel earned.',
  'Looking for the insight that\'s impossible to argue with.',
  'Checking if the brand genuinely owned the moment or borrowed it.',
  'Finding the claim that gets stronger under scrutiny.',
  'Asking if the campaign deserves the category it\'s entered in.',
  'Looking for the version of this that a tired jury still remembers.',
  'Checking whether the results match the ambition of the brief.',
  'Finding the headline that should probably open the entry.',
  'Asking if the campaign left the category better than it found it.',
  'Looking for the creative courage that the results actually prove.',
  'Checking if this is genuinely different or just well-produced.',
  'Finding the part that makes the rest of the entry make sense.',
  'Asking if the entry form is working as hard as the campaign did.',
  'Looking for the connection between strategy, creative, and result.',
  'Checking if this campaign solved a problem or created a platform.',
  'Finding the proof that this was the right answer, not just an answer.',
  'Asking whether the idea was born from the insight or bolted on.',
  'Looking for the executional detail only this brand could have done.',
  'Checking if the campaign would have worked without the big event.',
  'Finding the metric that proves the strategy was right all along.',
  'Asking if the story gets better or worse the more you know.',
  'Looking for the angle that turns a good case into a compelling one.',
  'Checking if the brand played a role or just played a budget.',
  'Finding the long-form evidence that backs the headline claim.',
  'Asking if there\'s a simpler story that\'s actually more impressive.',
  'Looking for the cultural shift that this campaign accelerated.',
  'Checking if the campaign was the cause or the beneficiary of timing.',
  'Finding the element that makes a jury want to see what came next.',
  'Asking if this is better than the previous campaign or just newer.',
  'Looking for the distinction between what was planned and what landed.',
  'Checking if the brand was brave or just given permission to be brave.',
  'Finding the one page of this that would win on its own.',
  'Asking if the insight could have led to a worse execution.',
  'Looking for what success would have looked like if results disappointed.',
  'Checking if the stated objectives were actually what mattered.',
  'Finding the result that proves the risk was worth taking.',
  'Asking if there\'s more creative ambition than the results justify.',
  'Looking for the distribution idea that deserves its own credit.',
  'Checking if this campaign is more interesting than its case study.',
  'Finding what a brand planner would have killed in a review.',
  'Asking if the most important decision was made before the brief.',
  'Looking for the version of this story that needs fewer caveats.',
  'Checking if the secondary results are doing too much work.',
  'Finding the genuine creative decision that drove the outcome.',
  'Asking if this would have been shortlisted five years ago too.',
  'Looking for the moment the idea became bigger than the brand.',
  'Checking if the problem was systemic or just a media moment.',
  'Finding the proof that the audience was actually paying attention.',
  'Asking if the reach was earned, bought, or politely exaggerated.',
  'Looking for the brand truth that the campaign kept coming back to.',
  'Checking if the competitive context makes the win look bigger.',
  'Finding what this work would need to be genuinely award-worthy.',
  'Asking if the idea could be stolen by a rival with a bigger budget.',
  'Looking for the proof that the campaign was more than a launch.',
  'Checking if the entry is asking for credit it genuinely deserves.',
  'Finding the part of this that couldn\'t have happened five years ago.',
  'Asking whether the brand character is consistent across all touchpoints.',
  'Looking for the evidence that the target audience genuinely responded.',
  'Checking if the campaign outcome was predictable or genuinely surprising.',
  'Finding the cultural credential that makes the claim feel authentic.',
  'Asking if the scale of the win matches the scale of the investment.',
  'Looking for the entry that\'s hiding inside the materials provided.',
  'Checking if this is a campaign story or a campaign highlight reel.',
  'Finding the proof that the idea scaled beyond its original medium.',
  'Asking if the brand comes out of this story looking deserving of it.',
  'Looking for the claim that\'s backed by the most credible evidence.',
  'Checking if the entry is as ambitious as the campaign it describes.',
  'Finding the moment where this stopped being a brief and became real.',
  'Asking if the best version of this story is already in here somewhere.',
  'Looking for the argument a defending judge would make in the room.',
  'Checking if this entry earns the shortlist it\'s probably expecting.',
  'Finding the diamond. Still looking. There\'s definitely one in here.',
]


// ─── Jury Eval ────────────────────────────────────────────────────────────────

export const JURY_EVAL_STATEMENTS: string[] = [
  'Asking what the person after lunch will say.',
  'Checking for the classic "but is it earned?" problem.',
  'Finding every reason a creative director will object.',
  'Imagining the juror who hates everything before awards.',
  'Asking if this survives the 11am attention span.',
  'Looking for the word "unprecedented" used incorrectly.',
  'Checking if the benchmark was chosen retroactively.',
  'Imagining the most cynical person in the room.',
  'Asking if the insight was really just the execution.',
  'Looking for the stat that doesn\'t quite add up.',
  'Checking if this has a real human in it anywhere.',
  'Asking: "but did it actually change behaviour though?"',
  'Finding the moment the jury starts checking phones.',
  'Checking if the cultural context section is defensible.',
  'Looking for the gap between the claim and evidence.',
  'Asking if this would win without the production budget.',
  'Simulating every "we\'ve seen this before" comment.',
  'Asking whether the case study made the work look better.',
  'Checking if the results section requires a footnote.',
  'Finding the slide that loses the room.',
  'Asking if this is a campaign or a PR stunt.',
  'Looking for strategic logic that holds under questioning.',
  'Checking if the celebrity was the idea or the crutch.',
  'Imagining the person who lobbies hardest against this.',
  'Asking what happens if you remove the production values.',
  'Checking if the target audience is just "everyone."',
  'Looking for tension between the brief and the execution.',
  'Asking if the innovation was the tech or the idea.',
  'Finding the line that sounds great but proves nothing.',
  'Simulating the shortlist discussion for this exact entry.',
  'Checking if the long-term results section is believable.',
  'Asking whether this is brave or just expensive.',
  'Looking for the claim that requires a very generous read.',
  'Finding what a rival agency would say in the room.',
  'Asking if this deserves Gold or just strong Silver energy.',
  'Checking whether the jury will remember this at 5pm.',
  'Looking for the "me too" version of this idea.',
  'Asking if the category is right or just advantageous.',
  'Finding every phrase that sounds like award-entry-speak.',
  'Checking if the idea could have come from anywhere.',
  'Asking if the results would impress without the backstory.',
  'Looking for the strategic claim that\'s actually a post-rationalisation.',
  'Checking if the earned media number includes paid coverage.',
  'Asking how many other entries this year look exactly like this.',
  'Finding the assumption that the whole case study rests on.',
  'Checking if "first ever" means globally or just in this market.',
  'Asking if the jury is being asked to reward the brief or the work.',
  'Looking for the result metric that was chosen after the campaign.',
  'Checking if the emotional claim has any behavioral evidence.',
  'Asking if this campaign solved a problem or briefly distracted from one.',
  'Finding the part of the case study that requires insider knowledge.',
  'Checking if the influencer reach is paid, organic, or optimistic.',
  'Asking what the competitor response was, and whether there was one.',
  'Looking for the claim that hasn\'t aged well since submission.',
  'Checking if this entry is stronger than the work it describes.',
  'Asking if there\'s a version of this that didn\'t need an awards budget.',
  'Finding the sentence that sounds better than it deserves to.',
  'Checking if the campaign idea could work for a different brand.',
  'Asking whether any of this would have happened without a deadline.',
  'Looking for the metric that was added after the results came in.',
  'Checking if this campaign interrupted the audience or invited them.',
  'Asking if "culturally relevant" is doing too much work in here.',
  'Finding the moment where the logic chain quietly breaks down.',
  'Checking if this jury has already given this brand enough medals.',
  'Asking if the market context section is accurate or just convenient.',
  'Looking for the strategic tension that was probably briefed later.',
  'Checking if the comparison benchmark is from the same universe.',
  'Asking if this is a case study or a highlight reel with data.',
  'Finding the use of "authentic" that nobody stopped to question.',
  'Checking if the results metric is correlated or causally linked.',
  'Asking if the campaign actually started a conversation or joined one.',
  'Looking for the part where the agency is taking credit for luck.',
  'Checking if this campaign would have worked before social media.',
  'Asking whether the size of the problem matches the size of the solution.',
  'Finding the claim that requires the most charitable interpretation.',
  'Checking if the audience insight would have surprised the audience.',
  'Asking if this brand had permission to have this conversation.',
  'Looking for the award-speak version of something simpler being said.',
  'Checking if this case study was written by the people who made it.',
  'Asking whether the results section contradicts the objectives section.',
  'Finding the part of this that a media planner would push back on.',
  'Checking if the human impact section is evidence or aspiration.',
  'Asking if the third-party validation is independent enough to count.',
  'Looking for the section that only makes sense to someone at the agency.',
  'Checking if the brand was brave or just permitted to borrow bravery.',
  'Asking whether the scale of the result is impressive in absolute terms.',
  'Finding the metric that the category chair will pull apart first.',
  'Checking if the innovation was the idea or the production method.',
  'Asking if this win required a structural advantage most brands don\'t have.',
  'Looking for the "first in category" claim that isn\'t quite first.',
  'Checking whether the campaign extended naturally or was force-extended.',
  'Asking if the audience could describe the campaign idea in one sentence.',
  'Finding the element that requires a footnote to not be misleading.',
  'Checking if the results are impressive even without the context framing.',
  'Asking whether this is a good campaign or a well-entered one.',
  'Looking for the part that was included to impress, not to inform.',
  'Checking if the timeline supports the cultural claim being made.',
  'Asking if the jury would have funded this if they\'d seen the brief.',
  'Finding the logic that felt tight in the room and reads loosely on paper.',
  'Checking if this entry can withstand the one person who knows the market.',
  'Asking if this has been entered before under a different name.',
  'Looking for the proof point that requires access to proprietary data.',
  'Checking if the target metric was the right metric all along.',
  'Asking if this campaign would exist without an awards entry deadline.',
  'Finding the place where scope was quietly expanded in the case study.',
  'Checking if the brand purpose is earned or just declared.',
  'Asking whether this campaign made the world better or just look better.',
  'Looking for the awards-friendly phrasing that obscures ordinary results.',
  'Checking if any of this is reproducible at a smaller budget.',
  'Asking if the case study is smarter than the campaign it describes.',
  'Finding the part of this that assumes the jury agrees with the brand.',
  'Checking if the creativity was in service of the strategy or despite it.',
  'Asking if this is a real insight or a sentence about people who buy things.',
  'Looking for the section that got weaker every time it was revised.',
  'Checking if the results truly outperformed or just performed adequately.',
  'Asking if the problem was important enough to justify a Grand Prix.',
  'Finding the cultural claim that needs a citation to be defensible.',
  'Checking if this campaign deserves the benefit of the doubt it\'s asking for.',
  'Asking if the brand was the hero of this story or just the sponsor.',
  'Looking for the part that a good editor would have cut before submission.',
  'Checking if the jury is being asked to judge the brief or the delivery.',
  'Asking whether the campaign outcome was proportionate to its visibility.',
  'Finding the result that was added to the case study after judging opened.',
  'Checking if every claim in the entry is supported by evidence in the entry.',
  'Asking if the audience awareness, preference, and purchase all moved together.',
  'Looking for the part that relies on the jury not knowing the market.',
  'Checking if this idea was possible only because of a specific budget threshold.',
  'Asking if the campaign result outlasted the campaign itself.',
  'Finding the section that would be embarrassing in a client debrief.',
  'Checking if the cultural moment was invented, intercepted, or coincidental.',
  'Asking if there\'s genuine craft or just quality production at scale.',
  'Looking for the logic that requires the jury to do some creative maths.',
  'Checking if this campaign earned its way into culture or bought a seat.',
  'Asking if the category entry is a first choice or a better-odds decision.',
  'Finding the word "innovative" applied to something recognisably familiar.',
  'Checking if the strategy section was written after the results came in.',
  'Asking if the problem was as dramatic in real life as it reads on the form.',
  'Looking for the target audience claim that covers too much demographic ground.',
  'Checking if the campaign\'s ambition and the campaign\'s execution are aligned.',
  'Asking if the bravest decision was made by the client or the agency.',
  'Finding every place where "insight" is doing the work of "observation."',
  'Checking if the media idea would have worked without the creative idea.',
  'Asking if the brand is more remembered or more respected after this.',
  'Looking for the results benchmark that was selected for maximum contrast.',
  'Checking if this is the best version of this type of entry this year.',
  'Asking if the cultural context section was added after the campaign ended.',
  'Finding the part of this entry that is demonstrably not standard practice.',
  'Checking if the creative platform has run long enough to prove itself.',
  'Asking whether the campaign drove change or surfed an existing wave.',
  'Looking for the claim that needs a footnote but doesn\'t have one.',
  'Checking if every agency on the credits is there for a reason.',
  'Asking if the campaign is brave or does it just look like it is.',
  'Finding the place where the evidence runs out and the conviction begins.',
  'Checking if the results were strong enough without the soft metrics.',
  'Asking if the consumer insight would have passed a research focus group.',
  'Looking for the one objection this entry hasn\'t thought to pre-empt.',
  'Checking if the claimed business impact is supported by the business.',
  'Asking if this is genuinely better than what won last year in this category.',
  'Finding the framing that makes average results look exceptional.',
  'Checking if the innovation claim could be disproven with a quick search.',
  'Asking if the creative work is as strong as the case study suggests it is.',
  'Looking for the section that made the agency feel better to write.',
  'Checking if this campaign was designed to win awards or to solve problems.',
  'Asking whether this jury owes this agency a medal or already gave them one.',
  'Finding the claim that the client\'s legal team probably pushed back on.',
  'Checking if the earned media figure includes any media the brand paid for.',
  'Asking if the results section tells the same story as the creative section.',
  'Looking for the part of this that assumes this market is like every market.',
  'Checking if the award would survive a journalist writing about it critically.',
  'Asking if this entry makes the jury feel smart or just feel convinced.',
  'Finding the evidence that the campaign was more than well-funded awareness.',
  'Checking if the secondary objectives section is hiding a weaker primary one.',
  'Asking if this campaign is as good as they think it is at 4am in Cannes.',
  'Looking for the logic that requires the jury to fill in some blanks.',
  'Checking if the scale of the award being sought matches the scale of the work.',
  'Asking whether the idea was strong enough to survive the client\'s changes.',
  'Finding the part of this that a competitor would call self-congratulatory.',
  'Checking if the claim that behaviour changed is backed by behavioral data.',
  'Asking if this would be a better entry in a different category.',
  'Looking for the section where honesty has been gently replaced by ambition.',
  'Checking if the metric used is the most meaningful or most flattering one.',
  'Asking if this entry would look different if it had been written by the client.',
  'Finding the moment this case study tips from confident into defensive.',
  'Checking if the campaign is the kind of thing this category should reward.',
  'Asking if the brand character is consistent or just consistent in the entry.',
  'Looking for the part that requires the jury to already like this brand.',
  'Checking if this won anywhere else and whether that should matter.',
  'Asking if the entry would still look strong if one key metric was removed.',
  'Finding the strategy claim that the creative team would find mildly surprising.',
  'Checking if the cultural relevance is global or just feels that way from here.',
  'Asking if the audience did this because of the brand or despite it being there.',
  'Looking for the tension between what the brief said and what the client wanted.',
  'Checking if the results have been independently verified or internally reported.',
  'Asking whether this campaign moved the needle on the problem that actually mattered.',
  'Finding the part of this entry that requires the most generosity to accept.',
  'Checking if this is an award worth giving or just an award that exists.',
  'Asking if the idea survived contact with the client and still looks like itself.',
  'Looking for every reason this doesn\'t win — then asking if they\'re disqualifying.',
  'Checking if the entry makes a case or just assumes it doesn\'t need to.',
  'Asking whether, if this wins, the right people are being recognised.',
]


// ─── Coach Review ─────────────────────────────────────────────────────────────

export const COACH_REVIEW_STATEMENTS: string[] = [
  'Looking for the thing you forgot to mention.',
  'Finding your strongest line that isn\'t your opener.',
  'Checking if your best proof point leads the story.',
  'Looking for where you undersell the hardest part.',
  'Finding the section a fresher pair of eyes sees differently.',
  'Asking if your insight is buried on slide twelve.',
  'Checking whether your results section is your opening.',
  'Looking for the thread that ties everything together.',
  'Finding the one line that makes juries lean forward.',
  'Asking if the human impact is clear enough.',
  'Checking if you buried the lede — because you probably did.',
  'Looking for the analogy that makes this land faster.',
  'Asking what a journalist would pull as the headline.',
  'Checking if the category narrative is being used well.',
  'Finding the part where you lost confidence and went vague.',
  'Looking for the claim that just needs one more proof point.',
  'Asking if the idea could be said in seven words.',
  'Checking for jargon that slows down non-native readers.',
  'Finding the genuine cultural insight that deserves more room.',
  'Looking for the transition that currently loses momentum.',
  'Asking whether the challenge section makes the win feel earned.',
  'Checking if the visuals match what the copy is claiming.',
  'Finding where brevity would serve you better than detail.',
  'Looking for the result that makes everything else click.',
  'Asking if the strategy section sounds like reverse engineering.',
  'Checking whether your tone matches the work\'s ambition.',
  'Finding the overlooked detail that actually makes this special.',
  'Asking if your execution proof is strong enough yet.',
  'Checking whether the timeline helps or just adds slides.',
  'Looking for the moment the jury\'s doubt turns to belief.',
  'Asking if the entry sounds as good as the work was.',
  'Finding the reframe that makes this more award-shaped.',
  'Checking whether the opening earns the attention it needs.',
  'Looking for the human story inside the strategy story.',
  'Asking if there\'s a smarter category for this idea.',
  'Checking for the section that sounds like a disclaimer.',
  'Finding the version of this that a juror quotes later.',
  'Asking if your strongest visual is in the right place.',
  'Checking that the case study doesn\'t outrun the evidence.',
  'Finding the angle that makes the jury say "oh, clever."',
  'Asking if you\'ve made the challenge sound hard enough.',
  'Looking for the sentence that should probably be the opener.',
  'Checking whether the proof you\'re most proud of is visible.',
  'Finding the word "significant" and replacing it with the number.',
  'Asking if the entry works for someone who\'s never heard of you.',
  'Looking for the part that assumes the jury did their homework.',
  'Checking if the creative idea is the star or supporting cast here.',
  'Finding the place where you stopped trusting the work and started explaining.',
  'Asking if the brief section makes the difficulty of this obvious.',
  'Looking for the result that makes a skeptic nod reluctantly.',
  'Checking if the context section is earning its word count.',
  'Finding the moment you can move to happen two paragraphs sooner.',
  'Asking if the long-term result is given the spotlight it deserves.',
  'Looking for the statistic that should be a sentence, not a footnote.',
  'Checking if your entry title is working as hard as it could be.',
  'Finding the reframe that changes how the whole story lands.',
  'Asking whether the tone of the entry matches the tone of the work.',
  'Looking for the connection between audience insight and creative decision.',
  'Checking if every section flows into the next without a bump.',
  'Finding the claim you made quietly that deserves to be made loudly.',
  'Asking if the timeline makes the speed of results more impressive.',
  'Looking for the comparison that makes the win feel more significant.',
  'Checking if the platform thinking is explained clearly enough.',
  'Finding the earned-media story that deserves more than a bullet point.',
  'Asking if the results hierarchy is ordered by most impressive first.',
  'Looking for the two sentences that should become the opening paragraph.',
  'Checking if the category description is working in your favour.',
  'Finding the audience-led evidence that anchors the whole strategy.',
  'Asking if the cultural tension is as clearly set up as it could be.',
  'Looking for the creative decision that shows genuine bravery.',
  'Checking if you\'ve named the client problem clearly enough upfront.',
  'Finding the part that reads like a credentials deck, not a case study.',
  'Asking if the closing section leaves the jury in the right place.',
  'Looking for the metric that would make a CFO raise an eyebrow pleasantly.',
  'Checking if the opening conflict is strong enough to justify the solution.',
  'Finding the transition where the story currently stalls.',
  'Asking if the sub-headings are doing any actual navigational work.',
  'Looking for the business problem that currently feels undersold.',
  'Checking if the campaign timeline makes the response time look impressive.',
  'Finding the audience reaction that should be centre stage.',
  'Asking if the strategic insight sounds proprietary or just observational.',
  'Looking for the section that\'s accurate but not useful.',
  'Checking whether the entry makes a case or just presents information.',
  'Finding the line that\'s technically true but structurally weak.',
  'Asking if your third result is actually more impressive than your first.',
  'Looking for the cultural permission slip that makes the idea make sense.',
  'Checking if the intro earns the entry without giving everything away.',
  'Finding the place where the story briefly becomes about the agency.',
  'Asking if the brand role is explained before the creative role.',
  'Looking for the executional proof that shows and doesn\'t just tell.',
  'Checking if the results section builds to a climax or just lists.',
  'Finding the moment you could lean into the unexpected outcome.',
  'Asking if the entry form field lengths are being used strategically.',
  'Looking for the voice that made the work special — is it in the entry?',
  'Checking whether your call-to-action in the closing is clear.',
  'Finding the nuance you cut for length that probably shouldn\'t have been cut.',
  'Asking if the three most impressive claims are the three that lead.',
  'Looking for the section that a sympathetic juror would want to quote.',
  'Checking whether this entry makes you want to see the work.',
  'Finding the detail that makes the claim feel earned rather than asserted.',
  'Asking if the audience\'s voice is present anywhere in this entry.',
  'Looking for the tension that makes the solution feel inevitable.',
  'Checking if the brief context makes the creative decision feel obvious.',
  'Finding the place where adding one more sentence would cost nothing.',
  'Asking whether the strategic ambition is clear in the first paragraph.',
  'Looking for the place where the work\'s actual beauty isn\'t coming through.',
  'Checking if the proof of concept is as strong as the concept itself.',
  'Finding the sentence that could be cut without losing anything.',
  'Asking if the media idea is being given enough credit separately.',
  'Looking for the word "leveraged" that could be replaced by something real.',
  'Checking if the opening statistic is the most arresting one available.',
  'Finding the cultural reference that makes the local market feel global.',
  'Asking if the proof of scale makes the scale actually feel impressive.',
  'Looking for the story arc that\'s almost there but not quite landed.',
  'Checking if the campaign mechanic is explained as simply as it could be.',
  'Finding the place where evidence trails off into assertion.',
  'Asking if the entry is asking for a Gold when a Grand Prix is possible.',
  'Looking for the comparison data that makes the result feel extraordinary.',
  'Checking if the written entry and the video entry tell the same story.',
  'Finding the secondary objective that\'s actually more impressive than the primary.',
  'Asking if the work\'s cultural impact has been undersold here.',
  'Looking for the third-party quote that validates the campaign\'s significance.',
  'Checking if the opening sentence gives the jury a reason to read on.',
  'Finding the strategic insight that deserves its own sentence, not just a clause.',
  'Asking if the entry is as confident as the work deserves it to be.',
  'Looking for the result where the industry benchmark makes you look brilliant.',
  'Checking if the brand\'s voice comes through in how the entry is written.',
  'Finding the place where a concrete example would replace a vague one.',
  'Asking if the problem was framed in human terms, not business ones.',
  'Looking for the executional detail that proves this wasn\'t templated.',
  'Checking if the campaign\'s longevity is being cited if it\'s an advantage.',
  'Finding the headline result that should be the very first sentence.',
  'Asking if the entry gives proper credit to what made the timing perfect.',
  'Looking for the reason a juror on the fence would tip toward voting yes.',
  'Checking if the results story ends on the strongest possible note.',
  'Finding the part of the strategy that sounds like insight, not hindsight.',
  'Asking if the creative ambition matches the problem\'s actual scale.',
  'Looking for the sentence that makes the jury feel the campaign was worth making.',
  'Checking whether you\'ve included everything that makes this remarkable.',
  'Finding the reason you entered this — and checking it\'s actually in here.',
  'Asking if the metrics hierarchy reflects the brief\'s actual priorities.',
  'Looking for the moment the entry shifts from describing to convincing.',
  'Checking if the evidence section reads like proof or just like data.',
  'Finding the claim that would be stronger with one supporting example.',
  'Asking if this entry would get a fair hearing in every regional market.',
  'Looking for the place where confidence could replace excessive qualification.',
  'Checking whether you\'ve made the jury feel the weight of the problem.',
  'Finding the idea\'s origin story — and whether it\'s in the entry yet.',
  'Asking if you\'ve named the category behaviour you were trying to change.',
  'Looking for the part that makes a first-time reader understand the context.',
  'Checking if the strategic recommendation section has a clear point of view.',
  'Finding where simplifying would make this more, not less, impressive.',
  'Asking if the competitive context makes the win feel more significant.',
  'Looking for the detail a juror would look up after reading the entry.',
  'Checking if the entry would still hold up if the supporting video was lost.',
  'Finding the creative decision that was the hardest to get approved.',
  'Asking if the brand benefit is clear before the consumer benefit is stated.',
  'Looking for the momentum-building moment in the middle of the entry.',
  'Checking if the results story is sequenced to build toward the biggest win.',
  'Finding the moment of genuine surprise that the entry hasn\'t fully leaned into.',
  'Asking if the reader\'s effort is being rewarded throughout the entry.',
  'Looking for the benchmark comparison that would make a juror\'s eyes widen.',
  'Checking whether the problem is framed in a way that makes the scale clear.',
  'Finding the section that\'s required reading vs. nice to have.',
  'Asking if the entry makes the jury feel like insiders, not just evaluators.',
  'Looking for the proof of audience transformation that goes beyond awareness.',
  'Checking if the category choice positions this as a standout or middle-of-pack.',
  'Finding the moment you forgot you were writing a case study and just told the truth.',
  'Asking if the entry earns confidence or just borrows it from the work.',
  'Looking for the sentence that a juror would screenshot and send to a colleague.',
  'Checking if the entry makes the brief feel like the right brief.',
  'Finding the piece of evidence that makes everything else in the entry make sense.',
  'Asking if the results section would survive being read in isolation.',
  'Looking for the tonal shift that currently disrupts the entry\'s momentum.',
  'Checking whether you\'ve demonstrated the why, not just the what.',
  'Finding the claim that needs unpacking — but hasn\'t been unpacked yet.',
  'Asking if the campaign\'s cultural contribution is visible or just assumed.',
  'Looking for the moment the jury would become advocates, not just approvers.',
  'Checking if the entry is written with the same confidence as the brief was pitched.',
  'Finding the three words a juror would use to describe this to the next room.',
  'Asking if the entry reads like a campaign worth celebrating.',
  'Looking for the creative brief\'s original tension — it\'s probably still useful.',
  'Checking if the most powerful sentence is where the most powerful sentence should be.',
  'Finding the place where a little more honesty would actually be more convincing.',
  'Asking if this entry makes the jury want the work to win.',
  'Looking for the gap between what was intended and what\'s been written here.',
  'Checking if the entry is as good as the campaign deserves it to be.',
  'Finding the section that would make a good juror argue in your favour.',
  'Asking if all the hard work that went into making this is visible here.',
  'Looking for the phrase that sounds like it came from a template — and replacing it.',
  'Checking if the entry is the best possible version of what you have.',
  'Finding the thing you know is true but haven\'t quite committed to saying.',
  'Asking if the entry leaves the jury excited or just satisfied.',
  'Looking for the structural move that would make this 30% more compelling.',
  'Checking if this entry makes the work look as good as the work actually was.',
  'Finding the moment of genuine creative courage that deserves the most credit.',
  'Asking if the entry has the same ambition as the campaign it describes.',
  'Looking for everything that makes this worth reading twice.',
  'Checking if the entry earns the medal it\'s asking for.',
  'Finding the best version of your argument — and making sure it\'s in here.',
]


// ─── Video Script — Generate Script ──────────────────────────────────────────

export const SCRIPT_GENERATE_STATEMENTS: string[] = [
  'Figuring out which parts actually matter here.',
  'Finding the version that works without local context.',
  'Asking what a juror in a different country needs.',
  'Building the arc a tired judge will follow easily.',
  'Deciding what the first ten seconds have to do.',
  'Trimming the parts that only make sense to you.',
  'Asking if the insight works without the market backstory.',
  'Building a story that explains itself without the VO.',
  'Finding where a foreign jury might nod off first.',
  'Deciding what one sentence does the heaviest lifting.',
  'Asking: does the problem land before the solution starts?',
  'Structuring the result so it doesn\'t need a footnote.',
  'Finding the simplest version of a complicated triumph.',
  'Building in the "why it matters" before anyone asks.',
  'Asking if this still makes sense at 1.5x speed.',
  'Deciding which stats survive and which ones clutter.',
  'Finding the emotional beat in an otherwise rational story.',
  'Asking what a juror in Tokyo needs to understand first.',
  'Structuring so the "so what" comes before the "how."',
  'Finding the transition that doesn\'t require a slide title.',
  'Asking if three minutes is enough — it will have to be.',
  'Building around the result that makes eyebrows go up.',
  'Finding the moment that makes context feel irrelevant.',
  'Deciding how to explain the market without losing the jury.',
  'Asking if this would work without the case study PDF.',
  'Structuring the opening to earn the next ninety seconds.',
  'Finding the proof that doesn\'t need translation.',
  'Building in the surprise before the jury expects it.',
  'Asking if the closing line actually lands like a closing line.',
  'Deciding what stays on screen vs. lives in the VO.',
  'Finding the arc that requires the least pre-existing knowledge.',
  'Asking if this script would survive with the sound off.',
  'Building the version a London jury and Seoul jury both get.',
  'Finding the cultural detail that translates rather than alienates.',
  'Deciding if the numbers need context or just confidence.',
  'Asking where a jury stops watching and starts judging.',
  'Structuring so the challenge earns the result\'s magnitude.',
  'Finding the through-line that makes edits feel impossible.',
  'Asking if this is three minutes or three minutes with padding.',
  'Building the version that makes the written entry feel redundant.',
  'Finding the opening image that makes stopping feel impossible.',
  'Deciding whether to lead with the problem or the human truth.',
  'Asking if the story works for someone who\'s never heard of this brand.',
  'Building the version where every second earns the next one.',
  'Finding the three-act structure hiding in these assets.',
  'Deciding which result to hold back for maximum impact.',
  'Asking if the VO is explaining what the visuals already show.',
  'Building the bridge between market context and jury comprehension.',
  'Finding the moment the audience did something — that\'s the story.',
  'Deciding if the brand needs to be named before the idea is clear.',
  'Asking if the tension in the first twenty seconds is strong enough.',
  'Building the sequence that makes the result feel inevitable in retrospect.',
  'Finding the emotional anchor that makes the data feel human.',
  'Deciding how much market context is essential vs. distracting.',
  'Asking if the pacing allows the best moment to breathe.',
  'Building around the insight that would land anywhere in the world.',
  'Finding the section that works harder as a visual than as a sentence.',
  'Deciding where the story turns — and whether it\'s early enough.',
  'Asking if the script is selling the work or the case for the work.',
  'Building the script that makes the next jury member lean forward.',
  'Finding the single most globally legible proof point in all of this.',
  'Deciding which sixty seconds a jury would quote later in the room.',
  'Asking if the result section deserves more than the final thirty seconds.',
  'Building the story in the order a first-time viewer would need it.',
  'Finding the connecting tissue between problem, idea, and outcome.',
  'Deciding if the human element comes early enough in the story.',
  'Asking if the pacing respects what the visuals are doing.',
  'Building around the scale of impact, not the scale of the campaign.',
  'Finding the moment that makes the scale feel real rather than reported.',
  'Deciding if the opening hook needs to be the problem or the promise.',
  'Asking whether the script is earning its runtime minute by minute.',
  'Building the version where less explanation means more understanding.',
  'Finding the narrative rhythm that matches the energy of the work.',
  'Deciding if the client brand needs a formal intro or just context.',
  'Asking if the script sequence mirrors how the jury will process it.',
  'Building in the stakes before the solution arrives.',
  'Finding the transition that makes the result feel like a release.',
  'Deciding if this is a story about a brand or a story about people.',
  'Asking if the key proof points are visible within thirty seconds of each other.',
  'Building the version where even the skeptical juror stays engaged.',
  'Finding the opening question the rest of the video answers.',
  'Deciding how many numbers is too many numbers in two minutes.',
  'Asking if the VO script and the visual script are telling the same story.',
  'Building the moment of payoff worthy of everything that comes before it.',
  'Finding the insight the jury will remember when they discuss this later.',
  'Deciding if the end card needs to be seen to be believed.',
  'Asking if the story has a villain as well as a hero and a resolution.',
  'Building the structure that works for a fast watch and a slower one.',
  'Finding the scene that proves the emotional claim being made elsewhere.',
  'Deciding if the music brief is locked into the narrative pacing.',
  'Asking if the script earns its length or could be tighter.',
  'Building in the human reaction that validates the scale of the problem.',
  'Finding the sentence that, read aloud, sets the whole tone correctly.',
  'Deciding which data point deserves a visual lockup vs. a VO mention.',
  'Asking if the opening image would still work as a final image.',
  'Building the version that doesn\'t need pause buttons or re-watches.',
  'Finding the part of the campaign story that didn\'t need to be told.',
  'Deciding if the problem needs to be shown before it can be talked about.',
  'Asking if the script can be followed by someone watching on mute.',
  'Building the arc that makes the result feel proportionate to the ambition.',
  'Finding the section that earns viewer trust before asking for it.',
  'Deciding how to sequence multiple proof points without losing momentum.',
  'Asking if the voiceover pacing matches the visual complexity onscreen.',
  'Building the story where the brand naturally belongs, not one it forced.',
  'Finding the single most compelling evidence of audience change in here.',
  'Deciding if the tension can be set up in the first sentence of VO.',
  'Asking whether the structure rewards the jury for watching to the end.',
  'Building the version where the data serves the emotion, not the other way.',
  'Finding the image that does the work of a paragraph of voiceover.',
  'Deciding if the cultural insight is universal enough to not need explanation.',
  'Asking if the problem section is dramatic enough to justify the solution.',
  'Building the narrative that makes a foreign jury feel the local stakes.',
  'Finding the audience behaviour change that makes the hardest argument.',
  'Deciding if the script is structured for emotion first, logic second.',
  'Asking if the first twenty seconds make someone want to see the next twenty.',
  'Building the script where every cut serves the story.',
  'Finding the sequence that earns the result before the result is shown.',
  'Deciding what the last thing a jury sees and hears should be.',
  'Asking if the end makes the beginning feel worth it.',
  'Building around the most credible version of the story available.',
  'Finding the cultural complexity that can be simplified without being lost.',
  'Deciding if the awards credentials should be in the script or just implied.',
  'Asking if the script is front-heavy with context and light on payoff.',
  'Building the structure that mirrors the brief\'s original ambition.',
  'Finding the result that a jury will spontaneously mention to their colleagues.',
  'Deciding if the pacing between sections is too quick or just efficient.',
  'Asking if the VO is doing too much work the visuals should be doing.',
  'Building the version that could win in a different award show too.',
  'Finding the cultural hook that makes a different-market juror feel included.',
  'Deciding if the script needs a title card or the VO handles context.',
  'Asking if the story has a beginning that earns the middle.',
  'Building around the part of this campaign that surprised even the agency.',
  'Finding where a more cinematic approach would serve the idea.',
  'Deciding if the brand\'s voice is present in the VO tone.',
  'Asking if the script\'s emotional arc peaks at the right moment.',
  'Building the version where silence does as much work as sound.',
  'Finding the section that would work better as a montage than a sequence.',
  'Deciding if the campaign mechanics need to be shown or just implied.',
  'Asking if the story earns the emotional payoff it\'s building toward.',
  'Building the script that would make the director feel excited.',
  'Finding where the current structure requires too much audience patience.',
  'Deciding if the script is building credibility at the right pace.',
  'Asking if the conclusion feels like an arrival or just a stop.',
  'Building the version that plays well in any room, anywhere in the world.',
  'Finding the moment the jury goes from understanding to believing.',
  'Deciding if the proof and the promise are in the right order here.',
  'Asking if the most human moment is also the most prominent one.',
  'Building around the core idea that survived every execution decision.',
  'Finding the three beats this script absolutely must hit.',
  'Deciding if the timeline makes the speed of achievement look impressive.',
  'Asking if the script delivers a story or just a summary.',
  'Building the version a jury would still be talking about after dinner.',
  'Finding the bridge that connects the local insight to the global stage.',
  'Deciding if the opening deserves to be more provocative.',
  'Asking if this script would survive without the campaign\'s name on it.',
  'Building the case that doesn\'t feel like it\'s making a case.',
  'Finding the sequence where the campaign\'s intelligence becomes obvious.',
  'Deciding if the VO is confident without being self-congratulatory.',
  'Asking if the script makes the jury feel like they discovered something.',
  'Building the version where form and content feel like the same decision.',
  'Finding the edit that makes the results section feel like a payoff.',
  'Deciding if the evidence is given the same visual weight as the idea.',
  'Asking if the most important visual is positioned where it deserves to be.',
  'Building the story that makes winning feel like the only logical outcome.',
  'Finding the beat that proves this deserved to be made.',
  'Deciding how to make a complex market feel simple without dumbing down.',
  'Asking if the narrative holds even when the visuals are generic.',
  'Building the structure that serves both a first watch and a second one.',
  'Finding the section where confidence could replace caution.',
  'Deciding if the strongest result should be the final image.',
  'Asking if the VO starts one sentence too late.',
  'Building the arc that makes the jury feel the problem was worth solving.',
  'Finding the three-word summary of what this script is actually about.',
  'Deciding if the energy of the work is captured in the energy of the script.',
  'Asking if the script is ready to be read aloud right now.',
  'Building the version where the jury finishes and immediately wants to discuss it.',
  'Finding the narrative frame that makes all the evidence feel connected.',
  'Deciding if the script could stand alone without the case study PDF.',
  'Asking if the story makes the brand the hero or just the host.',
  'Building the script that earns the result rather than just reporting it.',
  'Finding the opening that would be wrong to cut.',
  'Deciding if the VO rhythm allows the jury to absorb the key information.',
  'Asking if every visual is doing something the VO isn\'t already doing.',
  'Building the version where story momentum never stalls.',
  'Finding the sequence that proves the idea and the execution were inseparable.',
  'Deciding if the script needs more tension or more resolution.',
  'Asking if the final thirty seconds make the first thirty retroactively better.',
  'Building the story from the audience\'s point of view, not the agency\'s.',
  'Finding the edit decision that makes the whole thing feel effortless.',
  'Deciding what the jury should feel in the final three seconds.',
  'Asking if the script makes this campaign sound as good as it actually was.',
  'Building the version where the jury votes yes before the credits roll.',
  'Finding the version of this that no other campaign could have made.',
  'Deciding if the script is earning a Gold or asking for one.',
  'Asking if this script will still feel current when the jury watches it.',
  'Building the story that doesn\'t just show the work — it makes the case for it.',
  'Finding the sequence that makes the campaign feel genuinely remarkable.',
  'Deciding if the script needs one more revision or just one less line.',
  'Asking if this script does justice to everyone who made the campaign.',
  'Building the script that makes the jury wish they\'d worked on this.',
]


// ─── Video Script — Review Script ────────────────────────────────────────────

export const SCRIPT_REVIEW_STATEMENTS: string[] = [
  'Checking if minute one earns minute two.',
  'Looking for the line that every video also uses.',
  'Asking if this opens with a problem or a logo.',
  'Checking if the result arrives too late in the story.',
  'Looking for the four-word phrase that means nothing.',
  'Asking if "unprecedented" is doing any real work here.',
  'Checking whether this survives a fifteen-minute jury attention span.',
  'Looking for the script beat where the room checks phones.',
  'Asking if the insight is stated or just implied.',
  'Checking if the human story is real or a cameo.',
  'Looking for two minutes that could be ninety seconds.',
  'Asking if the VO is papering over weak visuals.',
  'Checking whether the ending actually lands or just stops.',
  'Looking for the trope list: data drought, then data flood.',
  'Asking if the challenge section is vivid enough to matter.',
  'Checking if the brand appears too early or too smugly.',
  'Looking for the section that exists only for the client.',
  'Asking how this sounds to someone who hates award videos.',
  'Checking if the pacing survives a tired Thursday afternoon jury.',
  'Looking for where the script asks for too much goodwill.',
  'Asking if your transitions are transitions or just title cards.',
  'Checking whether the music cue is doing emotional heavy lifting.',
  'Looking for the claim the visuals don\'t back up.',
  'Asking if this plays better with or without sound.',
  'Checking if the opening ten seconds are too slow to forgive.',
  'Looking for the line that will definitely prompt a wince.',
  'Asking if the script explains the idea or just describes it.',
  'Checking if this is a story or a highlight reel.',
  'Looking for the section where confidence tips into overselling.',
  'Asking whether a juror from outside your market follows this.',
  'Checking if every second is earning its place.',
  'Looking for the "change" or "transform" or "revolutionise" overuse.',
  'Asking if the brand benefit is ever shown, not just stated.',
  'Checking if the script would survive the video being muted.',
  'Looking for the beat where a sceptic stops believing.',
  'Asking if the result section arrives with enough build-up.',
  'Checking whether the tone matches the ambition of the work.',
  'Looking for the three seconds that could anchor the whole piece.',
  'Asking if this is trying to win an award or tell a story.',
  'Checking if this is as tight as it genuinely can be.',
  'Asking if the first sentence earns a second sentence.',
  'Looking for the VO line that a voiceover artist would hate reading.',
  'Checking if the cultural context section loses anyone outside the market.',
  'Asking whether the idea is clear by the thirty-second mark.',
  'Looking for the visual direction that\'s at odds with the VO tone.',
  'Checking if the result is as remarkable as the script implies it is.',
  'Asking if the jury has already seen this structure three times today.',
  'Looking for the moment the energy of the script drops noticeably.',
  'Checking if the problem setup is as strong as the solution payoff.',
  'Asking if the VO pacing allows the visuals room to land.',
  'Looking for the data point that arrives without any narrative setup.',
  'Checking if the human element in this script is more than a device.',
  'Asking whether the ending justifies the runtime that preceded it.',
  'Looking for the line that sounds like it was written last.',
  'Checking if the solution section explains what happened or just shows it.',
  'Asking if the story works for a juror watching their fourth video this hour.',
  'Looking for the transition that\'s actually just a gap.',
  'Checking if the biggest result is also the most prominent visually.',
  'Asking if the script makes a claim the visuals can\'t support.',
  'Looking for the section a fair editor would have cut in the room.',
  'Checking if the music is earning its emotional weight.',
  'Asking if the script trusts the audience enough to not over-explain.',
  'Looking for the part that sounds like it was written for the client, not the jury.',
  'Checking if the strategic context is legible to a non-industry viewer.',
  'Asking if the script is building toward something or just reporting everything.',
  'Looking for the moment where the pace doesn\'t match the content.',
  'Checking if the big reveal is set up well enough to land.',
  'Asking if this script would still feel fresh at the end of judging week.',
  'Looking for the cliché that has appeared in at least six other scripts this year.',
  'Checking if the voiceover rhythm helps or fights the visual rhythm.',
  'Asking if the brand name appears before the jury has a reason to care.',
  'Looking for the claim that requires knowledge the jury doesn\'t have.',
  'Checking if the challenge section makes the win feel proportionate.',
  'Asking whether this script would survive a re-edit with half the runtime.',
  'Looking for the statistics cluster that could be condensed to one strong number.',
  'Checking if the script\'s tone stays consistent across its full duration.',
  'Asking if the most important moment in the campaign is the most prominent moment in the script.',
  'Looking for the section that answers a question nobody asked.',
  'Checking if the emotional claim is validated somewhere in the visual sequence.',
  'Asking whether the script earns the music swell it\'s probably using.',
  'Looking for the VO sentence that says the same thing the previous one did.',
  'Checking if the opening image creates genuine curiosity.',
  'Asking if the pacing would work in a different language with longer subtitles.',
  'Looking for the moment the script tries to do too many things at once.',
  'Checking if the call to action has been cut, or if it should be.',
  'Asking if the script sounds like it believes what it\'s saying.',
  'Looking for the evidence that this script was edited, not just written.',
  'Checking if the result section has a narrative shape or just a structure.',
  'Asking if the juror understands the problem before the campaign appears.',
  'Looking for the line that would be stronger as a visual than a sentence.',
  'Checking if the product or service is introduced at the right point.',
  'Asking whether the script respects the jury\'s intelligence throughout.',
  'Looking for the section that makes a viewer grateful when it ends.',
  'Checking if the creative idea is visible anywhere in the script.',
  'Asking if the structure is logical, emotional, or accidentally neither.',
  'Looking for the visual sequence that the VO is competing with.',
  'Checking if the result metrics land with the weight they deserve.',
  'Asking if the script\'s conclusion makes the opening worth revisiting.',
  'Looking for the beat that would make a different editor celebrate.',
  'Checking if the story respects the audience that made the campaign possible.',
  'Asking if the VO sounds like something a human would actually say.',
  'Looking for the paragraph that does the job of the one before it.',
  'Checking if the problem framing is dramatic enough to justify the solution.',
  'Asking if the script would benefit from one fewer section.',
  'Looking for the line that was once a placeholder and never got replaced.',
  'Checking if the pacing in the problem section is as urgent as it should feel.',
  'Asking if the sequence of proof points is ordered for maximum impact.',
  'Looking for the section the director will find hardest to shoot.',
  'Checking if the script explains the market or just assumes the jury lives in it.',
  'Asking whether the script has a point of view or just a sequence of facts.',
  'Looking for the moment when even a sympathetic juror checks the runtime.',
  'Checking if the insight line is clear enough to be the script\'s spine.',
  'Asking if the ending is the right ending or just the last thing that was written.',
  'Looking for the visual instruction that\'s at odds with the emotional intention.',
  'Checking if the context section earns the result\'s emotional weight.',
  'Asking if the script has a voice, or just a neutral informational register.',
  'Looking for the VO line that could be the title of the whole entry.',
  'Checking if the brand\'s role in the story is active or just present.',
  'Asking if the script is as concise as the campaign deserves it to be.',
  'Looking for the place where a pause would do more than another sentence.',
  'Checking if the script pacing accounts for subtitles in the judging room.',
  'Asking if the script trusts the visuals to carry the moments they should.',
  'Looking for the structural choice that reveals when the script was last revised.',
  'Checking if the narrative hook would work even if the visuals weren\'t there.',
  'Asking if the script\'s ambition is proportionate to the campaign\'s evidence.',
  'Looking for the claim that requires a footnote that isn\'t there.',
  'Checking if the VO tone matches the visual world that\'s been created.',
  'Asking if the script earns its length or just fills it.',
  'Looking for the line that used to be longer and should have stayed that way.',
  'Checking if the sequence builds expectation before delivering on it.',
  'Asking if the script\'s emotional intelligence matches the campaign\'s emotional impact.',
  'Looking for the section where the script\'s confidence is slightly ahead of its evidence.',
  'Checking if this script would prompt a jury conversation or just a vote.',
  'Asking if the opening and the closing are in the same script tonally.',
  'Looking for the data visualisation moment that doesn\'t survive audio-only.',
  'Checking if every visual beat in the script has an emotional purpose.',
  'Asking if the script is too in love with the campaign to be honest about it.',
  'Looking for the secondary claim that\'s actually the most interesting claim.',
  'Checking if the VO uses "we" when "they" would be more powerful.',
  'Asking if the script would still hold up if the music was neutral.',
  'Looking for the moment the jury would feel the script lost its nerve.',
  'Checking if the result metrics are presented in the most legible order.',
  'Asking if the structure serves the story or just organises the information.',
  'Looking for the visual idea embedded in the script that deserves development.',
  'Checking if the VO acknowledges the audience before crediting the brand.',
  'Asking if the script is trying to explain too much in too little time.',
  'Looking for the line that will accidentally draw attention away from the visual.',
  'Checking if the script\'s final image is as strong as the final line.',
  'Asking if the emotional peak of the script is at the right timestamp.',
  'Looking for the section that belongs in the written entry, not the video.',
  'Checking if the creative idea lands before the strategy is explained.',
  'Asking if the script respects the jury\'s time in how it sequences information.',
  'Looking for the beat that creates genuine tension before the resolution.',
  'Checking if the narrative structure would survive a different editor\'s cut.',
  'Asking if every sentence in this script is pulling weight.',
  'Looking for the VO rhythm that would lose non-native English speakers.',
  'Checking if the script makes the campaign feel earned, not just explained.',
  'Asking if the first scene makes the jury want to solve the problem too.',
  'Looking for the moment the script stops being a story and becomes a list.',
  'Checking if the claim to cultural impact is shown or just stated.',
  'Asking if this would still feel like a strong entry at 4pm on a Friday.',
  'Looking for the section that should be on screen, not in the VO.',
  'Checking if the result section lands with the same voice as the problem section.',
  'Asking if the script proves the idea or just describes what happened.',
  'Looking for the pacing decision that currently costs the script its momentum.',
  'Checking whether this script makes the jury want to vote or just move on.',
  'Asking if the script has been read aloud at the pace it will be delivered.',
  'Looking for the line that makes everything after it slightly less believable.',
  'Checking if the script\'s energy builds to a climax or just runs level.',
  'Asking if the ending could be stronger without changing the preceding ninety seconds.',
  'Looking for the visual sequence that makes the VO redundant in the best way.',
  'Checking if the first three seconds justify the jury staying for the rest.',
  'Asking if the script treats the jury as intelligent and appropriately sceptical.',
  'Looking for the place where one specific human example would replace three statistics.',
  'Checking if the script would hold up in a room with bad speakers.',
  'Asking if the creative surprise in the campaign is also a surprise in the script.',
  'Looking for the transition that currently makes the story feel stitched rather than flowing.',
  'Checking if the script\'s final argument is the strongest argument.',
  'Asking if this script makes the jury feel the campaign deserved to exist.',
  'Looking for the pacing issue that would be obvious in the edit suite.',
  'Checking if the problem section makes a neutral viewer want a solution.',
  'Asking if the script earns every second of its runtime.',
  'Looking for the strategic claim made confidently but evidenced lightly.',
  'Checking if the brand is introduced at the right moment in the narrative.',
  'Asking if the most compelling visual moment is supported by the most compelling VO line.',
  'Looking for the section that was clearly added after the first draft was too short.',
  'Checking if the script\'s structure is clear enough that the edit will be obvious.',
  'Asking if the script makes the result feel inevitable or just reported.',
  'Looking for the VO line that\'s slightly more honest than the rest of the script.',
  'Checking if the ending rewards the jury for watching the whole thing.',
  'Asking if the script makes this campaign look as remarkable as it probably was.',
  'Looking for one cut that would make every remaining second stronger.',
  'Checking if the script earns the result it\'s about to report.',
  'Asking if the jury would describe this video as compelling or comprehensive.',
  'Looking for the version of this script that wins, not just submits.',
  'Checking if this script is as good as the campaign it\'s trying to represent.',
  'Asking if the final line is the one this script was always building toward.',
  'Looking for the remaining thing a good script editor would have caught.',
  'Checking if this script makes the jury feel the work deserved to be made.',
  'Asking if this is the script that wins, or the first draft of the script that wins.',
]
