// lib/project-page-shared.ts — extracted from app/projects/[id]/page.tsx
// (refactor-r1r2-tabs-2026-07-13 build fix). Next.js App Router page.tsx
// files may only export `default` + the sanctioned page-export allowlist;
// these were runtime value exports (COLLAB_TYPE_LABELS, materialWordCount,
// buildAnalysisText) that tripped "X is not a valid Page export field" in
// the Vercel build (a next-build-specific check plain tsc doesn't catch).
// Moved here verbatim, no behavior change. Types imported back from
// page.tsx are type-only (erased at compile time), so this creates no
// runtime circular dependency with the page.

import type { Material, ScriptAnalysis } from '@/app/projects/[id]/page'

// ── Collaborator ──────────────────────────────────────────────────────────────
export type CollabType =
  | 'lead_agency' | 'creative_agency' | 'media_agency'
  | 'production_company' | 'pr_agency' | 'brand_team' | 'tech_partner' | 'other'

export const COLLAB_TYPE_LABELS: Record<CollabType, string> = {
  lead_agency:        'Lead Agency',
  creative_agency:    'Creative Agency',
  media_agency:       'Media Agency',
  production_company: 'Production Company',
  pr_agency:          'PR Agency',
  brand_team:         'Brand / Client Team',
  tech_partner:       'Technology Partner',
  other:              'Other',
}

// Session 52 (P-03): page load no longer fetches extracted_text — materials
// arrive as slim metadata with has_text/text_words. Fresh uploads this session
// still carry extracted_text in memory. ALWAYS use these helpers instead of
// checking m.extracted_text directly for gating/badges/word counts.
export const materialWordCount = (m: Material): number =>
  typeof m.text_words === 'number'
    ? m.text_words
    : (m.extracted_text || '').trim().split(/\s+/).filter(Boolean).length

export function buildAnalysisText(
  analysis: ScriptAnalysis,
  campaignName: string,
  show: string,
  category: string
): string {
  const lines = [
    'SCRIPT ANALYSIS REPORT',
    '================================',
    `Project:  ${campaignName}`,
    ...(show ? [`Show:     ${show}`] : []),
    ...(category ? [`Category: ${category}`] : []),
    '',
    'OVERALL ASSESSMENT',
    '================================',
    analysis.summary,
    '',
  ]
  if (analysis.key_improvements.length > 0) {
    lines.push('KEY IMPROVEMENTS', '================================')
    analysis.key_improvements.forEach((item, i) => {
      lines.push(`${i + 1}. ${item}`)
    })
    lines.push('')
  }
  if (analysis.changes.length > 0) {
    lines.push('SCENE-BY-SCENE CHANGES', '================================')
    analysis.changes.forEach((change, i) => {
      lines.push(`\n[${i + 1}] ${change.section}`)
      if (change.original) lines.push(`Original: "${change.original}"`)
      lines.push(`Rationale: ${change.reason}`)
    })
    lines.push('')
  }
  lines.push('---', 'Generated by Shortlist · shortlist.app')
  return lines.join('\n')
}
