'use client'

// ─── NextStepCard (Build 2, Session 55 — Brief-Onboarding-Engagement-v3 §5) ──
// Rendered at the end of judge evaluation results. Shows up to 2 alternate
// show/category placements generated by evaluate-entry (next_opportunities,
// candidates enforced server-side), the strongest already-generated
// directions by category fit, and a workflow CTA into Directions.
//
// Session 55 feedback round (Ben):
// - Visually prominent: green-tinted card with a strong green border. NOT the
//   dark-green/bone treatment, which is reserved for guidance nudges (Build 3)
//   so product output and guidance stay visually distinct.
// - Score-aware framing: a 6.5 is "in contention, not comfortable" per the
//   evaluate-entry calibration anchors. The intro says so plainly and frames
//   the suggestions as alternatives, not bonuses.
// - Existing directions first: if generated directions already rank stronger
//   placements (higher category fit), surface them with fit % and deep-link.
// - CTA logic: the generate button only appears when NO directions exist.
//   With directions, the single CTA returns the user to them.
//
// Rules (binding, from the v3 brief):
// - This card is PRODUCT OUTPUT, not guidance. It does NOT respect the
//   guidance toggle. Never gate it on guidance_enabled.
// - Renders ONLY when `opportunities` is a real array (the eval carried the
//   field). An evaluation without the field (pre-Build-2 evals, or evals run
//   before the frontend shipped candidates) renders nothing.
// - An EMPTY array is valid: the model found no stronger placements. The card
//   then renders the score framing + workflow CTA only.
// - No data access of its own (A-08 discipline) — everything via props.
// - No hover-dependent content; tap targets ≥ 44px. No em-dashes in copy.

import { useEffect, useRef } from 'react'

export type NextStepOpportunity = {
  show: string
  category: string
  rationale: string
  // Set by the page when a direction already exists for this show
  // (deep-link CTA instead of generate CTA)
  existingDirectionId?: number | null
}

// An already-generated direction that ranks a stronger placement
export type NextStepDirectionRef = {
  id: number
  name: string
  show: string | null
  category: string | null
  fit: number | null // win_likelihood column = Category Fit (0–100)
}

export type NextStepAction =
  | { type: 'view_directions' }
  | { type: 'generate_directions' }
  | { type: 'view_direction'; directionId: number; source: 'opportunity' | 'existing'; show?: string; category?: string }

type NextStepCardProps = {
  // null = field absent on this evaluation → render nothing
  opportunities: NextStepOpportunity[] | null
  evaluatedShow: string
  overallScore: number | null
  // true when the project has at least one generated (non-quick-eval) direction
  hasDirections: boolean
  // Strongest existing directions by category fit (page filters to those
  // ranking HIGHER than the evaluated placement; may be empty)
  strongerDirections: NextStepDirectionRef[]
  // Fired once per mount (page logs nextstep_shown)
  onShown: (opportunityCount: number) => void
  // Fired on any CTA (page logs nextstep_clicked + navigates)
  onAction: (action: NextStepAction) => void
}

const TAP_TARGET = { minHeight: '44px' } as const

// Score framing follows the evaluate-entry calibration anchors:
// 8+ = shortlist/medal contention; 6–7.9 = in contention with real gaps;
// <6 = not shortlist-ready at this show.
function introCopy(score: number | null, show: string, hasOpportunities: boolean): string {
  const showName = show || 'this show'
  if (score === null) {
    return hasOpportunities
      ? 'Based on the entry as written, the work shows signals for other placements:'
      : 'Most entries have more than one viable placement. Directions maps them for this campaign.'
  }
  const s = score.toFixed(1)
  if (score >= 8) {
    return hasOpportunities
      ? `This entry scored ${s} against the ${showName} jury standard. It is in genuine contention there. Based on the entry as written, the work also shows signals for:`
      : `This entry scored ${s} against the ${showName} jury standard. It is in genuine contention there. Directions maps any further placements for this campaign.`
  }
  if (score >= 6) {
    return hasOpportunities
      ? `This entry scored ${s} against the ${showName} jury standard. That is in contention, but not a comfortable position. Based on the entry as written, the work shows stronger signals elsewhere:`
      : `This entry scored ${s} against the ${showName} jury standard. That is in contention, but not a comfortable position. Most entries have more than one viable placement. Directions maps them for this campaign.`
  }
  return hasOpportunities
    ? `This entry scored ${s} against the ${showName} jury standard. At that level, ${showName} is unlikely to be the right home for this work as written. Consider these placements:`
    : `This entry scored ${s} against the ${showName} jury standard. At that level, ${showName} is unlikely to be the right home for this work as written. Directions maps where else this campaign can compete.`
}

export default function NextStepCard({
  opportunities,
  evaluatedShow,
  overallScore,
  hasDirections,
  strongerDirections,
  onShown,
  onAction,
}: NextStepCardProps) {
  const shownRef = useRef(false)

  useEffect(() => {
    if (opportunities === null) return
    if (shownRef.current) return
    shownRef.current = true
    onShown(opportunities.length)
    // Fire-once per mount by design; onShown identity changes are irrelevant.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [opportunities === null])

  if (opportunities === null) return null

  const hasOpportunities = opportunities.length > 0
  const hasStronger = strongerDirections.length > 0

  return (
    <div className="mt-5 rounded-xl border-2 border-green-700 bg-green-50 p-4 sm:p-5">
      <div
        className="text-green-800 mb-2"
        style={{ fontFamily: '"Instrument Serif", "Times New Roman", serif', fontSize: '1.55rem', lineHeight: 1.15, letterSpacing: '-0.01em' }}
      >
        ✦ Where this campaign goes next
      </div>

      <p className="text-sm text-gray-800 mb-3 leading-relaxed">
        {introCopy(overallScore, evaluatedShow, hasOpportunities)}
      </p>

      {hasOpportunities && (
        <ul className="space-y-3 mb-4">
          {opportunities.map((opp, i) => (
            <li key={`${opp.show}-${opp.category}-${i}`} className="bg-white border border-green-200 rounded-lg px-4 py-3">
              <span className="text-sm font-semibold text-gray-900">
                {opp.show}
                {opp.category ? ` · ${opp.category}.` : '.'}
              </span>
              {opp.rationale ? (
                <span className="text-sm text-gray-700"> {opp.rationale}</span>
              ) : null}
              {opp.existingDirectionId ? (
                <div>
                  <button
                    type="button"
                    onClick={() =>
                      onAction({
                        type: 'view_direction',
                        directionId: opp.existingDirectionId as number,
                        source: 'opportunity',
                        show: opp.show,
                        category: opp.category,
                      })
                    }
                    className="text-sm text-green-700 hover:text-green-600 font-medium underline-offset-2 hover:underline"
                    style={TAP_TARGET}
                  >
                    You already have a direction for this show. View it →
                  </button>
                </div>
              ) : null}
            </li>
          ))}
        </ul>
      )}

      {/* Existing directions that rank stronger placements (Ben, Session 55:
          point users back to what fit higher before they chase new ground) */}
      {hasStronger && (
        <div className="mb-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">
            Already mapped in your Directions
          </p>
          <p className="text-sm text-gray-800 mb-2 leading-relaxed">
            Your generated directions ranked {strongerDirections.length > 1 ? 'these placements' : 'this placement'} higher on category fit:
          </p>
          <ul className="space-y-2">
            {strongerDirections.map(dir => (
              <li key={dir.id}>
                <button
                  type="button"
                  onClick={() =>
                    onAction({
                      type: 'view_direction',
                      directionId: dir.id,
                      source: 'existing',
                      show: dir.show ?? undefined,
                      category: dir.category ?? undefined,
                    })
                  }
                  className="w-full text-left bg-white border border-green-200 hover:border-green-500 rounded-lg px-4 py-3 transition-colors"
                  style={TAP_TARGET}
                >
                  <span className="text-sm font-semibold text-gray-900">{dir.name}</span>
                  <span className="text-sm text-gray-600">
                    {dir.show ? ` · ${dir.show}` : ''}
                    {dir.category ? ` · ${dir.category}` : ''}
                  </span>
                  {typeof dir.fit === 'number' && (
                    <span className={`text-sm font-semibold tabular-nums ml-2 ${dir.fit >= 70 ? 'text-green-700' : dir.fit >= 45 ? 'text-amber-700' : 'text-red-600'}`}>
                      {dir.fit}% fit
                    </span>
                  )}
                  <span className="text-sm text-green-700 font-medium"> · View →</span>
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-2">
        {hasDirections ? (
          <button
            type="button"
            onClick={() => onAction({ type: 'view_directions' })}
            className="px-4 py-2 bg-green-800 hover:bg-green-700 text-white text-sm font-medium rounded-md"
            style={TAP_TARGET}
          >
            See your Entry Directions →
          </button>
        ) : (
          <button
            type="button"
            onClick={() => onAction({ type: 'generate_directions' })}
            className="px-4 py-2 bg-green-800 hover:bg-green-700 text-white text-sm font-medium rounded-md"
            style={TAP_TARGET}
          >
            Generate directions for this campaign
          </button>
        )}
      </div>

      <p className="text-xs text-gray-500 mt-3">
        Placement suggestions are based on the entry as written, not your campaign brief.
        {hasDirections ? ' Your existing directions were mapped from the campaign itself.' : ''}
      </p>
    </div>
  )
}
