'use client'

// ─── NextStepCard (Build 2, Session 55 — Brief-Onboarding-Engagement-v3 §5) ──
// Rendered at the end of judge evaluation results. Shows up to 2 alternate
// show/category placements generated by evaluate-entry (next_opportunities,
// candidates enforced server-side) plus a workflow CTA into Directions.
//
// Rules (binding, from the v3 brief):
// - This card is PRODUCT OUTPUT, not guidance. It does NOT respect the
//   guidance toggle. Never gate it on guidance_enabled.
// - Renders ONLY when `opportunities` is a real array (the eval carried the
//   field). An evaluation without the field (pre-Build-2 evals, or evals run
//   before the frontend shipped candidates) renders nothing.
// - An EMPTY array is valid: the model found no stronger placements. The card
//   then renders the workflow CTA only.
// - No data access of its own (A-08 discipline) — everything via props.
// - No hover-dependent content; tap targets ≥ 44px.

import { useEffect, useRef } from 'react'

export type NextStepOpportunity = {
  show: string
  category: string
  rationale: string
  // Set by the page when a direction already exists for this show
  // (deep-link CTA instead of generate CTA)
  existingDirectionId?: number | null
}

export type NextStepAction =
  | { type: 'view_directions' }
  | { type: 'generate_directions' }
  | { type: 'view_direction'; directionId: number; opportunity: NextStepOpportunity }

type NextStepCardProps = {
  // null = field absent on this evaluation → render nothing
  opportunities: NextStepOpportunity[] | null
  evaluatedShow: string
  overallScore: number | null
  // true when the project has at least one generated (non-quick-eval) direction
  hasDirections: boolean
  // Fired once per mount (page logs nextstep_shown)
  onShown: (opportunityCount: number) => void
  // Fired on any CTA (page logs nextstep_clicked + navigates)
  onAction: (action: NextStepAction) => void
}

const TAP_TARGET = { minHeight: '44px' } as const

export default function NextStepCard({
  opportunities,
  evaluatedShow,
  overallScore,
  hasDirections,
  onShown,
  onAction,
}: NextStepCardProps) {
  const shownRef = useRef(false)

  useEffect(() => {
    if (opportunities === null) return
    if (shownRef.current) return
    shownRef.current = true
    onShown(opportunities.length)
    // Fire-once per mount by design; onShown identity changes are irrelevant.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [opportunities === null])

  if (opportunities === null) return null

  const hasOpportunities = opportunities.length > 0

  return (
    <div className="mt-4 bg-white border border-gray-200 rounded-lg p-4">
      <div className="text-xs font-semibold uppercase tracking-wide text-green-700 mb-2">
        Where this campaign goes next
      </div>

      {hasOpportunities ? (
        <>
          <p className="text-sm text-gray-700 mb-3">
            {typeof overallScore === 'number'
              ? `This entry scored ${overallScore.toFixed(1)} against the ${evaluatedShow} jury standard. Based on the work itself, it shows strong signals for ${opportunities.length > 1 ? 'two other placements' : 'another placement'}:`
              : `Based on the work itself, this entry shows strong signals for ${opportunities.length > 1 ? 'two other placements' : 'another placement'}:`}
          </p>
          <ul className="space-y-3 mb-4">
            {opportunities.map((opp, i) => (
              <li key={`${opp.show}-${opp.category}-${i}`} className="flex items-start gap-2">
                <span className="text-green-700 mt-0.5" aria-hidden="true">•</span>
                <div className="min-w-0">
                  <span className="text-sm font-semibold text-gray-900">
                    {opp.show}
                    {opp.category ? ` · ${opp.category}.` : '.'}
                  </span>
                  {opp.rationale ? (
                    <span className="text-sm text-gray-700"> {opp.rationale}</span>
                  ) : null}
                  {opp.existingDirectionId ? (
                    <div>
                      <button
                        type="button"
                        onClick={() =>
                          onAction({
                            type: 'view_direction',
                            directionId: opp.existingDirectionId as number,
                            opportunity: opp,
                          })
                        }
                        className="text-sm text-green-700 hover:text-green-600 font-medium underline-offset-2 hover:underline"
                        style={TAP_TARGET}
                      >
                        View this direction →
                      </button>
                    </div>
                  ) : null}
                </div>
              </li>
            ))}
          </ul>
        </>
      ) : (
        <p className="text-sm text-gray-700 mb-4">
          Most entries have more than one viable placement. Directions maps them for this campaign.
        </p>
      )}

      <div className="flex flex-wrap items-center gap-2">
        {hasDirections ? (
          <>
            <button
              type="button"
              onClick={() => onAction({ type: 'view_directions' })}
              className="px-4 py-2 bg-green-800 hover:bg-green-700 text-white text-sm font-medium rounded-md"
              style={TAP_TARGET}
            >
              See your Entry Directions →
            </button>
            <button
              type="button"
              onClick={() => onAction({ type: 'generate_directions' })}
              className="px-4 py-2 bg-white border border-gray-300 text-gray-700 hover:text-gray-900 text-sm font-medium rounded-md"
              style={TAP_TARGET}
            >
              Generate directions for this campaign
            </button>
          </>
        ) : (
          <>
            <button
              type="button"
              onClick={() => onAction({ type: 'generate_directions' })}
              className="px-4 py-2 bg-green-800 hover:bg-green-700 text-white text-sm font-medium rounded-md"
              style={TAP_TARGET}
            >
              Generate directions for this campaign
            </button>
            <button
              type="button"
              onClick={() => onAction({ type: 'view_directions' })}
              className="px-4 py-2 bg-white border border-gray-300 text-gray-700 hover:text-gray-900 text-sm font-medium rounded-md"
              style={TAP_TARGET}
            >
              Open the Directions tab
            </button>
          </>
        )}
      </div>
    </div>
  )
}
