-- ============================================================================
-- Session 51 — Baseline DDL generator (audit DM-01)
--
-- Reconstructs the live public-schema DDL from the Postgres catalogs:
-- extensions, tables, constraints, indexes, functions, triggers (incl. the
-- handle_new_user trigger on auth.users), views, RLS enablement, policies,
-- and table/column grants for anon + authenticated.
--
-- HOW TO USE (one pass):
--   1. Paste this ENTIRE script into Supabase SQL Editor and Run.
--      It is a single SELECT — read-only, zero risk.
--   2. The result is one row per DDL object, in dependency order.
--   3. Click "Download CSV" on the results panel.
--   4. Drop the CSV into the Shortlist App folder and tell Claude —
--      it gets assembled and committed as migrations/000-baseline.sql.
--
-- This is the SQL-editor substitute for `supabase db dump --schema public`.
-- When the CLI is set up, regenerate with the real dump and replace.
-- ============================================================================

WITH

-- ── 1. Extensions ───────────────────────────────────────────────────────────
ext AS (
  SELECT 1 AS section, extname::text AS obj,
         'CREATE EXTENSION IF NOT EXISTS "' || extname || '";' AS ddl
  FROM pg_extension
  WHERE extname NOT IN ('plpgsql')
),

-- ── 2. Tables (columns, defaults, identity, generated, NOT NULL) ───────────
tbl AS (
  SELECT 2 AS section, c.relname::text AS obj,
         'CREATE TABLE ' || quote_ident(c.relname) || ' (' || E'\n' ||
         string_agg(
           '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod) ||
           CASE
             WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
             WHEN a.attidentity  = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
             WHEN a.attidentity  = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
             WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
             ELSE ''
           END ||
           CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
           E',\n' ORDER BY a.attnum
         ) || E'\n);' AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid = c.oid AND ad.adnum = a.attnum
  WHERE n.nspname = 'public' AND c.relkind = 'r'
  GROUP BY c.relname
),

-- ── 3. Constraints (PK → UNIQUE → CHECK → FK, so FKs come last) ────────────
con AS (
  SELECT 3 AS section,
         t.relname::text || '.' ||
           CASE con.contype WHEN 'p' THEN '1' WHEN 'u' THEN '2' WHEN 'c' THEN '3' ELSE '4' END ||
           '.' || con.conname AS obj,
         'ALTER TABLE ' || quote_ident(t.relname) || ' ADD CONSTRAINT ' ||
         quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';' AS ddl
  FROM pg_constraint con
  JOIN pg_class t ON t.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public' AND con.contype IN ('p', 'u', 'c', 'f')
),

-- ── 4. Indexes not backing a constraint ─────────────────────────────────────
idx AS (
  SELECT 4 AS section, i.indexrelid::regclass::text AS obj,
         pg_get_indexdef(i.indexrelid) || ';' AS ddl
  FROM pg_index i
  JOIN pg_class c ON c.oid = i.indrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND NOT EXISTS (SELECT 1 FROM pg_constraint cc WHERE cc.conindid = i.indexrelid)
),

-- ── 5. Functions and procedures (excluding extension-owned) ─────────────────
fn AS (
  SELECT 5 AS section, p.proname::text AS obj,
         pg_get_functiondef(p.oid) || ';' AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (
      SELECT 1 FROM pg_depend d
      WHERE d.objid = p.oid AND d.deptype = 'e'
    )
),

-- ── 6. Triggers on public tables + the auth.users signup trigger ───────────
trg AS (
  SELECT 6 AS section, tg.tgname::text AS obj,
         pg_get_triggerdef(tg.oid) || ';' AS ddl
  FROM pg_trigger tg
  JOIN pg_class c ON c.oid = tg.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE NOT tg.tgisinternal
    AND (n.nspname = 'public' OR (n.nspname = 'auth' AND c.relname = 'users'))
),

-- ── 7. Views ────────────────────────────────────────────────────────────────
vw AS (
  SELECT 7 AS section, viewname::text AS obj,
         'CREATE OR REPLACE VIEW ' || quote_ident(viewname) || ' AS' || E'\n' ||
         pg_get_viewdef(('public.' || quote_ident(viewname))::regclass, true) AS ddl
  FROM pg_views
  WHERE schemaname = 'public'
),

-- ── 8. RLS enablement ───────────────────────────────────────────────────────
rls AS (
  SELECT 8 AS section, c.relname::text AS obj,
         'ALTER TABLE ' || quote_ident(c.relname) || ' ENABLE ROW LEVEL SECURITY;' AS ddl
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
),

-- ── 9. Policies ─────────────────────────────────────────────────────────────
pol AS (
  SELECT 9 AS section, tablename::text || '.' || policyname AS obj,
         'CREATE POLICY ' || quote_ident(policyname) || ' ON ' || quote_ident(tablename) ||
         ' AS ' || permissive ||
         ' FOR ' || cmd ||
         ' TO ' || array_to_string(roles, ', ') ||
         coalesce(' USING (' || qual || ')', '') ||
         coalesce(' WITH CHECK (' || with_check || ')', '') || ';' AS ddl
  FROM pg_policies
  WHERE schemaname = 'public'
),

-- ── 10. Table-level grants for anon / authenticated ─────────────────────────
gr AS (
  SELECT 10 AS section, table_name::text || '.' || grantee AS obj,
         'GRANT ' || string_agg(privilege_type, ', ' ORDER BY privilege_type) ||
         ' ON ' || quote_ident(table_name) || ' TO ' || grantee || ';' AS ddl
  FROM information_schema.role_table_grants
  WHERE table_schema = 'public' AND grantee IN ('anon', 'authenticated')
  GROUP BY table_name, grantee
),

-- ── 11. Column-level grants for anon / authenticated ────────────────────────
-- Only columns where the table-level grant does NOT already cover the
-- privilege (e.g. profiles UPDATE limited to full_name/avatar_url).
cgr AS (
  SELECT 11 AS section, cp.table_name::text || '.' || cp.grantee || '.' || cp.privilege_type AS obj,
         'GRANT ' || cp.privilege_type || ' (' ||
         string_agg(quote_ident(cp.column_name), ', ' ORDER BY cp.column_name) ||
         ') ON ' || quote_ident(cp.table_name) || ' TO ' || cp.grantee || ';' AS ddl
  FROM information_schema.column_privileges cp
  WHERE cp.table_schema = 'public'
    AND cp.grantee IN ('anon', 'authenticated')
    AND NOT EXISTS (
      SELECT 1 FROM information_schema.role_table_grants g
      WHERE g.table_schema = 'public'
        AND g.table_name = cp.table_name
        AND g.grantee = cp.grantee
        AND g.privilege_type = cp.privilege_type
    )
  GROUP BY cp.table_name, cp.grantee, cp.privilege_type
)

SELECT section, obj, ddl
FROM (
  SELECT * FROM ext
  UNION ALL SELECT * FROM tbl
  UNION ALL SELECT * FROM con
  UNION ALL SELECT * FROM idx
  UNION ALL SELECT * FROM fn
  UNION ALL SELECT * FROM trg
  UNION ALL SELECT * FROM vw
  UNION ALL SELECT * FROM rls
  UNION ALL SELECT * FROM pol
  UNION ALL SELECT * FROM gr
  UNION ALL SELECT * FROM cgr
) all_ddl
ORDER BY section, obj;
